name: CI

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - uses: actions/setup-go@v5
      - name: Install deps
        run: >-
          python -m pip install --upgrade pip &&
          pip install twine==5.1.1 build==1.2.2.post1
      - name: Build
        run: python -m build --wheel
      - name: Upload
        run: twine upload dist/*
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
